data class Post(
    var id : Long = 0,
    val ownerId : Long,
    var fromId : Long,
    var createdBy : Long,
    var date : Long,
    var text : String,
    var replyOwnerId : Long,
    var replyPostId : Long,
    var friendsOnly : Boolean,
    val comments : Comments,
    val copyright : Copyright,
    val likes : Likes,
    val reposts : Reposts,
    val views : Views,
    val postType : String,
    val signerId : Long,
    val canPin : Boolean,
    val canDelete : Boolean,
    val canEdit : Boolean,
    val isPinned : Boolean,
    val markedAsAds : Boolean,
    val isFavorite : Boolean,
    val donut : Donut,
    val postponedId : Long
)